### ISSUE TITLE
Add token.mat to .gitignore file.

### ISSUE THREAD

**Issue by ghost** [pranshu0210/ml-andrew-ng#1]
After a successful submission, the submit script saves a file named `token.mat` to the same directory.
`token.mat` has your email address and a token using which you upload **your** submissions.
If anyone clones this repository and executes submit, he/she might be submitting the solution using your credentials **unknowingly**. It is a bad practice to commit private tokens and/or access keys to a public repository like this.

Read more about `.gitignore` file and `git rm` command to solve this issue.

**Comment by pranshu0210** [comment]
The issue has been resolved. Thanks bud for pointing it out!

**Comment by ghost** [comment]
You might want to know about `file glob` support in gitignore. As you will add more exercises, you will find yourself copying and pasting `machine-learning-ex#/ex#/token.mat` to gitignore, which is an anti-pattern (**D**on't **R**epeat **Y**ourself).

**Comment by pranshu0210** [comment]
Okay, will check it out.
